### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by MrBrooks89** [sanjai-AK47/Probuster#3]
Didn't see anywhere listed if this was only for a certain OS. I was able to install probuster using windows terminal via pip3 install git+https://github.com/sanjai-AK47/Probuster.git but doesn't run with flags -h or doc. This is what I am getting:
![probuster issue](https://github.com/sanjai-AK47/Probuster/assets/52933386/2a3b38fa-cb93-4c3f-9f93-84a93b69c3e7)
I have my python script directory in PATH environment variables and other python scripts work such as uro, dirsearch etc.

Works fine with kali using WSL so I'll be testing it out that way but would be nice to run it in windows terminal directly. Thanks for the awesome program.

**Comment by RevoltSecurities** [comment]
Hey @ericbrooks269 ,

Thanks for creating your issue and clear explanations, after reviewing the attached image , I confirm that probuster is installed properly in every OS and The problem you are facing is missing some core package that required by probuster,
so Im mention some pkg that and install with `pip install ` command.
```
dnspython
async_dns
aiodns
aiodnsresolver
```
so these are some packages , Try to install these package then try to execute the probuster again, if you encountering
the same issue please let me know.

**Comment by MrBrooks89** [comment]
Thanks for getting back quickly. That was it just missing those packages. Probuster is working now.

**Comment by RevoltSecurities** [comment]
Hey @ericbrooks269 ,

Happy to hear that probuster working find and good now, Thank you for choosing our tools for you Hacking

Kind regards,
@sanjai-AK47
